@extends('layouts.dashboard')
@section('title', 'Admin dashboard')
@section('content')
    <h1>Admin dashboard</h1><p class="lead">Manage subadmins and assign students to their account manager.</p>
    <div class="grid"><div class="card"><div class="stat">{{ $subadmins->count() }}</div><p>Subadmins</p></div><div class="card"><div class="stat">{{ $students->count() }}</div><p>Students</p></div><div class="card"><a class="button" href="{{ route('admin.subadmins.create') }}">Add subadmin</a><p>Create a staff account.</p></div></div>
    <h2>Subadmins</h2>
    <table><thead><tr><th>Name</th><th>Email</th><th>Mobile</th><th>Assigned students</th><th>Actions</th></tr></thead><tbody>@forelse($subadmins as $subadmin)<tr><td>{{ $subadmin->name }}</td><td>{{ $subadmin->email }}</td><td>{{ $subadmin->mobile }}</td><td>{{ $subadmin->assigned_students_count }}</td><td><a class="button secondary" href="{{ route('admin.users.edit', $subadmin) }}">Edit</a> <form method="POST" action="{{ route('admin.users.destroy', $subadmin) }}" style="display:inline" onsubmit="return confirm('Delete this subadmin? Their students will become unassigned.')">@csrf @method('DELETE')<button class="button" style="background:#b42318">Delete</button></form></td></tr>@empty<tr><td colspan="5">No subadmins created yet.</td></tr>@endforelse</tbody></table>
    <h2>Students</h2>
    <table><thead><tr><th>Student</th><th>Mobile</th><th>Work status</th><th>Progress</th><th>Assign subadmin</th><th>Actions</th></tr></thead><tbody>@forelse($students as $student)<tr><td>{{ $student->name }}<br><small>{{ $student->email }}</small></td><td>{{ $student->mobile }}</td><td>{{ ucfirst($student->work_status) }}</td><td>{{ $student->progress }}%</td><td><form method="POST" action="{{ route('admin.students.assign', $student) }}">@csrf @method('PATCH')<select class="form-control" name="assigned_subadmin_id" onchange="this.form.submit()"><option value="">Unassigned</option>@foreach($subadmins as $subadmin)<option value="{{ $subadmin->id }}" @selected($student->assigned_subadmin_id === $subadmin->id)>{{ $subadmin->name }}</option>@endforeach</select></form></td><td><a class="button secondary" href="{{ route('admin.users.edit', $student) }}">Edit</a> <form method="POST" action="{{ route('admin.users.destroy', $student) }}" style="display:inline" onsubmit="return confirm('Delete this student?')">@csrf @method('DELETE')<button class="button" style="background:#b42318">Delete</button></form></td></tr>@empty<tr><td colspan="6">No students registered yet.</td></tr>@endforelse</tbody></table>
@endsection
